#ifndef GAME_CONFIG_HPP
#define GAME_CONFIG_HPP

// SELECT JUST ONE MODE
//#define GAME_2D_CONFIGURATION
#define GAME_3D_CONFIGURATION


// INITIAL SCREEN DIMENSIONS
#define GAME_INITIAL_SCREEN_WIDTH 960
#define GAME_INITIAL_SCREEN_HEIGHT 540


// RENDER ASPECT, CURRENT BASE: 16:9   ->   1920/1080
#define GAME_BASE_RENDER_SCREEN_WIDTH 1920
#define GAME_BASE_RENDER_SCREEN_HEIGHT 1080


#endif // GAME_CONFIG_HPP
