set(COSMIC_PROJECT_NAME "NetworkDemo")
set(COSMIC_PROJECT_MODE GAME_3D_CONFIGURATION)
set(COSMIC_PROJECT_FIRST_SCENE_HEADER "scenes/network_demo_scene.hpp")
set(COSMIC_PROJECT_FIRST_SCENE_CLASS "NetworkDemoScene")
set(COSMIC_PROJECT_EXECUTABLE_NAME "NetworkDemo")
set(COSMIC_PROJECT_WINDOW_TITLE "NetworkDemo")
set(COSMIC_PROJECT_WINDOW_ICON_PATH "")
set(COSMIC_PROJECT_INITIAL_SCREEN_WIDTH 800)
set(COSMIC_PROJECT_INITIAL_SCREEN_HEIGHT 600)
set(COSMIC_PROJECT_BASE_RENDER_SCREEN_WIDTH 1920)
set(COSMIC_PROJECT_BASE_RENDER_SCREEN_HEIGHT 1080)
set(COSMIC_PROJECT_VIEWPORT_SCALE_TO_WINDOW ON)
set(COSMIC_PROJECT_WINDOW_RESIZABLE ON)
set(COSMIC_PROJECT_WINDOW_LOCK_BASE_RENDER_ASPECT ON)
set(COSMIC_PROJECT_START_FULLSCREEN OFF)
set(COSMIC_PROJECT_START_VSYNC OFF)
set(COSMIC_PROJECT_ASSET_DIR "assets")

set(COSMIC_PROJECT_SOURCE_FILES
    scenes/network_demo_scene.cpp
    entities/network_demo_player.cpp
    entities/network_demo_projectile.cpp
)