set(COSMIC_PROJECT_NAME "BasicDemo_2D")
set(COSMIC_PROJECT_MODE GAME_2D_CONFIGURATION)
set(COSMIC_PROJECT_FIRST_SCENE_HEADER "scenes/main_scene.hpp")
set(COSMIC_PROJECT_FIRST_SCENE_CLASS "MainScene")
set(COSMIC_PROJECT_EXECUTABLE_NAME "BasicDemo_2D")
set(COSMIC_PROJECT_WINDOW_TITLE "BasicDemo 2D")
set(COSMIC_PROJECT_WINDOW_ICON_PATH "")
set(COSMIC_PROJECT_INITIAL_SCREEN_WIDTH 1920)
set(COSMIC_PROJECT_INITIAL_SCREEN_HEIGHT 1080)
set(COSMIC_PROJECT_BASE_RENDER_SCREEN_WIDTH 1920)
set(COSMIC_PROJECT_BASE_RENDER_SCREEN_HEIGHT 1080)
set(COSMIC_PROJECT_START_FULLSCREEN OFF)
set(COSMIC_PROJECT_START_VSYNC OFF)
set(COSMIC_PROJECT_ASSET_DIR "assets")

set(COSMIC_PROJECT_SOURCE_FILES
    scenes/main_scene.cpp
    entities/json_demo_object.cpp
)