set(COSMIC_PROJECT_NAME "Bench3D")
set(COSMIC_PROJECT_MODE GAME_3D_CONFIGURATION)
set(COSMIC_PROJECT_FIRST_SCENE_HEADER "../Bench2D/scenes/bench_scene.hpp")
set(COSMIC_PROJECT_FIRST_SCENE_CLASS "Bench::BenchScene")
set(COSMIC_PROJECT_EXECUTABLE_NAME "Bench3D")
set(COSMIC_PROJECT_WINDOW_TITLE "CosmicEngine Bench 3D")
set(COSMIC_PROJECT_INITIAL_SCREEN_WIDTH 1280)
set(COSMIC_PROJECT_INITIAL_SCREEN_HEIGHT 720)
set(COSMIC_PROJECT_BASE_RENDER_SCREEN_WIDTH 1280)
set(COSMIC_PROJECT_BASE_RENDER_SCREEN_HEIGHT 720)
set(COSMIC_PROJECT_VIEWPORT_SCALE_TO_WINDOW OFF)
set(COSMIC_PROJECT_WINDOW_RESIZABLE OFF)
set(COSMIC_PROJECT_WINDOW_LOCK_BASE_RENDER_ASPECT OFF)
set(COSMIC_PROJECT_START_FULLSCREEN OFF)
set(COSMIC_PROJECT_START_VSYNC OFF)
set(COSMIC_PROJECT_ASSET_DIR "../Bench2D/assets")

# Shares the benchmark sources with Bench2D; the 3D branches are selected at compile time.
set(COSMIC_PROJECT_SOURCE_FILES
    ../Bench2D/scenes/bench_scene.cpp
    ../Bench2D/entities/bench_object.cpp
    ../Bench2D/utilities/bench_state.cpp
    ../Bench2D/utilities/sysinfo.cpp
)
