set(COSMIC_PROJECT_NAME "BasicDemo_3D")
set(COSMIC_PROJECT_MODE GAME_3D_CONFIGURATION)
set(COSMIC_PROJECT_FIRST_SCENE_HEADER "scenes/main_scene.hpp")
set(COSMIC_PROJECT_FIRST_SCENE_CLASS "MainScene")
set(COSMIC_PROJECT_EXECUTABLE_NAME "BasicDemo_3D")
set(COSMIC_PROJECT_WINDOW_TITLE "BasicDemo 3D")
set(COSMIC_PROJECT_WINDOW_ICON_PATH "")
set(COSMIC_PROJECT_INITIAL_SCREEN_WIDTH 1920)
set(COSMIC_PROJECT_INITIAL_SCREEN_HEIGHT 1080)
set(COSMIC_PROJECT_BASE_RENDER_SCREEN_WIDTH 1920)
set(COSMIC_PROJECT_BASE_RENDER_SCREEN_HEIGHT 1080)
set(COSMIC_PROJECT_VIEWPORT_SCALE_TO_WINDOW OFF)
set(COSMIC_PROJECT_WINDOW_RESIZABLE ON)
set(COSMIC_PROJECT_WINDOW_LOCK_BASE_RENDER_ASPECT OFF)
set(COSMIC_PROJECT_START_FULLSCREEN OFF)
set(COSMIC_PROJECT_START_VSYNC OFF)
set(COSMIC_PROJECT_ASSET_DIR "assets")

set(COSMIC_PROJECT_SOURCE_FILES
    scenes/main_scene.cpp
    entities/collision_demo_object_3d.cpp
)