set(COSMIC_PROJECT_NAME "Bench2D")
set(COSMIC_PROJECT_MODE GAME_2D_CONFIGURATION)
set(COSMIC_PROJECT_FIRST_SCENE_HEADER "scenes/bench_scene.hpp")
set(COSMIC_PROJECT_FIRST_SCENE_CLASS "Bench::BenchScene")
set(COSMIC_PROJECT_EXECUTABLE_NAME "Bench2D")
set(COSMIC_PROJECT_WINDOW_TITLE "CosmicEngine Bench 2D")
set(COSMIC_PROJECT_INITIAL_SCREEN_WIDTH 1280)
set(COSMIC_PROJECT_INITIAL_SCREEN_HEIGHT 720)
set(COSMIC_PROJECT_BASE_RENDER_SCREEN_WIDTH 1280)
set(COSMIC_PROJECT_BASE_RENDER_SCREEN_HEIGHT 720)
set(COSMIC_PROJECT_VIEWPORT_SCALE_TO_WINDOW OFF)
set(COSMIC_PROJECT_WINDOW_RESIZABLE OFF)
set(COSMIC_PROJECT_WINDOW_LOCK_BASE_RENDER_ASPECT OFF)
set(COSMIC_PROJECT_START_FULLSCREEN OFF)
set(COSMIC_PROJECT_START_VSYNC OFF)
set(COSMIC_PROJECT_ASSET_DIR "assets")

set(COSMIC_PROJECT_SOURCE_FILES
    scenes/bench_scene.cpp
    entities/bench_object.cpp
    utilities/bench_state.cpp
    utilities/sysinfo.cpp
)
