set(COSMIC_PROJECT_NAME "sandbox_3D")
set(COSMIC_PROJECT_MODE GAME_3D_CONFIGURATION)
set(COSMIC_PROJECT_FIRST_SCENE_HEADER "scenes/sandbox_scene_3d.hpp")
set(COSMIC_PROJECT_FIRST_SCENE_CLASS "Sandbox3DScene")
set(COSMIC_PROJECT_EXECUTABLE_NAME "sandbox_3D")
set(COSMIC_PROJECT_WINDOW_TITLE "sandbox 3D")
set(COSMIC_PROJECT_WINDOW_ICON_PATH "assets/textures/cube_test.png")
set(COSMIC_PROJECT_INITIAL_SCREEN_WIDTH 1920)
set(COSMIC_PROJECT_INITIAL_SCREEN_HEIGHT 1080)
set(COSMIC_PROJECT_BASE_RENDER_SCREEN_WIDTH 1920)
set(COSMIC_PROJECT_BASE_RENDER_SCREEN_HEIGHT 1080)
set(COSMIC_PROJECT_VIEWPORT_SCALE_TO_WINDOW OFF)
set(COSMIC_PROJECT_WINDOW_RESIZABLE ON)
set(COSMIC_PROJECT_WINDOW_LOCK_BASE_RENDER_ASPECT OFF)
set(COSMIC_PROJECT_START_FULLSCREEN ON)
set(COSMIC_PROJECT_START_VSYNC ON)
set(COSMIC_PROJECT_ASSET_DIR "assets")

set(COSMIC_PROJECT_SOURCE_FILES
    scenes/sandbox_scene_3d.cpp
    entities/sandbox_rotating_cube_object_3d.cpp
    entities/sandbox_hammer_object_3d.cpp
    entities/sandbox_light_object_3d.cpp
)