set(COSMIC_PROJECT_NAME "MiniScene")
set(COSMIC_PROJECT_MODE GAME_2D_CONFIGURATION)
set(COSMIC_PROJECT_FIRST_SCENE_HEADER "scenes/mini_scene.hpp")
set(COSMIC_PROJECT_FIRST_SCENE_CLASS "MiniScene::MiniScene")
set(COSMIC_PROJECT_EXECUTABLE_NAME "MiniScene")
set(COSMIC_PROJECT_WINDOW_TITLE "MiniScene")
set(COSMIC_PROJECT_INITIAL_SCREEN_WIDTH 800)
set(COSMIC_PROJECT_INITIAL_SCREEN_HEIGHT 600)
set(COSMIC_PROJECT_BASE_RENDER_SCREEN_WIDTH 800)
set(COSMIC_PROJECT_BASE_RENDER_SCREEN_HEIGHT 600)
set(COSMIC_PROJECT_START_FULLSCREEN OFF)
set(COSMIC_PROJECT_START_VSYNC ON)
set(COSMIC_PROJECT_ASSET_DIR "assets")

set(COSMIC_PROJECT_SOURCE_FILES
    scenes/mini_scene.cpp
    entities/player_object.cpp
    entities/obstacle_object.cpp
)
